apiVersion: v1
kind: Service
metadata:
  name: ngnix
  labels:
    io.kompose.service: ngnix
  {{- include "ngnix.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
spec:
  type: {{ .Values.ngnix.type }}
  selector:
    io.kompose.service: ngnix
  {{- include "ngnix.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ngnix.ports | toYaml | nindent 2 -}}