drupalFpm:
  drupalFpm:
    image:
      repository: rishabgit/drupal-docker
      tag: php-fpm
  replicas: 1
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  type: ClusterIP
kubernetesClusterDomain: cluster.local
