version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"

  drupal-fpm:
    image: drupal:10.0.10-php8.2-fpm-alpine3.18
    container_name: drupal-fpm
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ./app:/var/www/html

  ngnix:
    image: nginx:alpine-perl
    container_name: ngnix
    depends_on:
      - drupal-fpm
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx-conf:/etc/nginx/conf.d
    networks:
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  app:
  db-data:
