apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    io.kompose.service: phpmyadmin
  {{- include "phpmyadmin.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
spec:
  type: {{ .Values.phpmyadmin.type }}
  selector:
    io.kompose.service: phpmyadmin
  {{- include "phpmyadmin.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.phpmyadmin.ports | toYaml | nindent 2 -}}