apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: external
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/external: "true"
  podSelector:
    matchLabels:
      io.kompose.network/external: "true"
