apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: drupal-fpm
  name: drupal-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: drupal-fpm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/external: "true"
        io.kompose.network/internal: "true"
        io.kompose.service: drupal-fpm
        app: drupal-fpm
    spec:
      containers:
        - env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: env
            - name: DRUPAL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DRUPAL_PASSWORD
                  name: env
            - name: DRUPAL_USER
              valueFrom:
                configMapKeyRef:
                  key: DRUPAL_USER
                  name: env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env
            - name: SITE_NAME
              valueFrom:
                configMapKeyRef:
                  key: SITE_NAME
                  name: env
            - name: KS
              valueFrom:
                configMapKeyRef:
                  key: KS
                  name: env
          image: rishabgit/drupal-docker:php-fpm
          name: drupal-fpm
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: drupal-fpm-claim0
      restartPolicy: Always
      volumes:
        - name: drupal-fpm-claim0
          persistentVolumeClaim:
            claimName: drupal-fpm-claim0
status: {}
