apiVersion: v1
kind: Service
metadata:
  name: drupal-fpm
  labels:
    io.kompose.service: drupal-fpm
  {{- include "drupal-fpm.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
spec:
  type: {{ .Values.drupalFpm.type }}
  selector:
    io.kompose.service: drupal-fpm
  {{- include "drupal-fpm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.drupalFpm.ports | toYaml | nindent 2 -}}

